[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "phronesitron"
authors = ["Reto Stamm"]
description = "Interact with ML language models from the commandline"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.1"
keywords = ["openai", "literature"]
license = "GPL-3"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "wheel",
    "openai",
    "argparse",
    "datetime",
    "pyperclip",
    "pdfminer.six",
    "termcolor",
]

homepage="https://github.com/retospect/phronesitron"

[project.scripts]
ph = "phronesitron.phronesitron:ph_main"

[tool.bumpver]
current_version = "0.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"src/phronesitron/__init__.py" = ["{version}"]

